
services:
  loki:
    image: grafana/loki:2.9.0
    user: "0:0" 
    command: -config.file=/etc/loki/loki-config.yml
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yml
      - loki-index:/loki/index
      - loki-cache:/loki/cache
      - loki-chunks:/loki/chunks
      - loki-compactor:/loki/compactor
    ports:
      - "3100:3100"


  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - backend-logs:/code/logs
    command: -config.file=/etc/promtail/config.yml


  grafana:
    image: grafana/grafana:10.2.3
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin


volumes:
  backend-logs: 
    external: true
  loki-index:
    driver: local
  loki-cache:
    driver: local
  loki-chunks:
    driver: local
  loki-compactor:
    driver: local