server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: backend
    static_configs:
      - targets:
          - localhost
        labels:
          job: backend
          __path__: /code/logs/combined.log

    pipeline_stages:
      # 1. Regex para separar time, level e message
      - regex:
          expression: '^(?P<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) \[[^\]]*(?P<level>info|warn|error)[^\]]*\]: (?P<message>.*)$'

      # 2. Remove cores ANSI do level
      - replace:
          source: level
          target: level
          expression: '\x1b\[[0-9;]*m'
          replace: ''

      # 3. Remove cores ANSI da message
      - replace:
          source: message
          target: message
          expression: '\x1b\[[0-9;]*m'
          replace: ''

      # 4. Cria labels no Loki
      - labels:
          level: ""
